### ISSUE TITLE
Static link to edictor data

### ISSUE THREAD

**Issue by LinguList** [LanguageStructure/KAHD_pre_release#1]
```
https://lingulist.de/edictor/?file=arawa&remote_dbase=arawa&publish=true&preview=500&css=menu:hide|textfields:hide&columns=DOCULECT|CONCEPT|FORM|TOKENS|COGID|COGIDS|ALIGNMENT&basics=DOCULECT|CONCEPT|FORM|TOKENS|COGID
```

This app allows people to scroll through the data, investigate alignments, but not modify entries.

**Comment by LanguageStructure** [comment]
could the alignements also be displayed?

I will use the link for the article, instead of the static version.

Thank you

**Comment by LinguList** [comment]
The alignments are there by right mouse click. Displaying them does not make this much better. But just change the URL here: `basics=DOCULECT|CONCEPT|FORM|TOKENS|COGID|ALIGNMENT`
