### ISSUE TITLE
CLDF Checks: Please add concept list to the Concepticon projects via the normal review procedure

### ISSUE THREAD

**Issue by LinguList** [LanguageStructure/KAHD_pre_release#10]

**Comment by LanguageStructure** [comment]
I am not sure how to do this

**Comment by LinguList** [comment]
we have done it for you.

**Comment by LinguList** [comment]
We made an official concept list and submitted it to concepticon where it was reviewed and errors were spotted, so that the new conceptt list now has only 705 concepts.

**Comment by LanguageStructure** [comment]
Thanks!
